export enum statusPedido{
    PENDENTE = 'PENDENTE',
	FINALIZADO = 'FINALIZADO',
	CANCELADO = 'CANCELADO',
	NAO_ENVIADO = 'NAO_ENVIADO',
	DEVOLUCAO = 'DEVOLUCAO',
	ENVIADO = 'ENVIADO',
	RECEBIDO = 'RECEBIDO',
	AVALIADO = 'AVALIADO'
}